# Generated by Django 4.2.19 on 2025-03-02 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_pk', models.IntegerField()),
                ('game_date', models.DateField()),
                ('winner_t_id', models.IntegerField()),
                ('home_team_power', models.FloatField()),
                ('away_team_power', models.FloatField()),
                ('is_winner_home_team', models.BooleanField()),
                ('home_starter_id', models.IntegerField()),
                ('away_starter_id', models.IntegerField()),
                ('home_team_id', models.IntegerField()),
                ('away_team_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('p_name', models.TextField(max_length=100)),
                ('handed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PitcherStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('stat_date', models.DateField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('era', models.FloatField()),
                ('so', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField()),
                ('t_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.TextField()),
                ('stat_date', models.DateField()),
                ('overall_wins', models.IntegerField()),
                ('overall_losses', models.IntegerField()),
                ('home_wins', models.IntegerField()),
                ('home_losses', models.IntegerField()),
                ('away_wins', models.IntegerField()),
                ('away_losses', models.IntegerField()),
                ('left_handed_wins', models.IntegerField()),
                ('left_handed_losses', models.IntegerField()),
                ('right_handed_wins', models.IntegerField()),
                ('right_handed_losses', models.IntegerField()),
                ('last_10_wins', models.IntegerField()),
                ('last_10_losses', models.IntegerField()),
                ('diff', models.IntegerField()),
                ('streak_is_win', models.BooleanField()),
                ('streak', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_win_point_weight', models.FloatField()),
                ('last_10_winning_weight', models.FloatField()),
                ('home_or_away_winning_weight', models.FloatField()),
                ('pitcher_handed_winning_weight', models.FloatField()),
                ('overall_winning_weight', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
